name: baidu_connector
description: Baidu Netdisk storage connector for MVision.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  knowledge_core:
    path: ../../knowledge_core
  platform_api:
    path: ../../platform_api
  dio: ^5.4.0
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.0
