import 'package:freezed_annotation/freezed_annotation.dart';
import 'source_reference.dart';
import 'patch_risk_level.dart';

part 'wiki_patch.freezed.dart';
part 'wiki_patch.g.dart';

/// A file-level patch operation.
@freezed
class FilePatch with _$FilePatch {
  const factory FilePatch({
    /// Target file path (must be in wiki/ directory).
    required String path,

    /// Type of operation.
    required FilePatchOperation operation,

    /// Content to write (for create/update).
    String? content,

    /// Original content (for diff display).
    String? originalContent,
  }) = _FilePatch;

  factory FilePatch.fromJson(Map<String, dynamic> json) =>
      _$FilePatchFromJson(json);
}

/// Type of file patch operation.
enum FilePatchOperation {
  /// Create a new file.
  create,

  /// Update an existing file.
  update,

  /// Delete a file.
  delete,

  /// Move/rename a file.
  move,
}

/// A Wiki patch generated by LLM for review.
///
/// Patch is an independent entity before being written to disk.
/// It must pass validation before being applied.
@freezed
class WikiPatch with _$WikiPatch {
  const factory WikiPatch({
    /// Unique patch ID.
    required String id,

    /// List of file patches.
    required List<FilePatch> files,

    /// References to source documents.
    required List<SourceReference> references,

    /// Summary of changes.
    required String summary,

    /// Risk level of this patch.
    required PatchRiskLevel riskLevel,

    /// When the patch was created.
    required DateTime createdAt,

    /// Whether the patch has been applied.
    @Default(false) bool applied,

    /// When the patch was applied (if applicable).
    DateTime? appliedAt,
  }) = _WikiPatch;

  factory WikiPatch.fromJson(Map<String, dynamic> json) =>
      _$WikiPatchFromJson(json);
}
